branch-defaults:
  develop:
    environment: development
    group_suffix: null
  master:
    environment: production
    group_suffix: null
global:
  application_name: eb-with-monorepo
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 12
  default_region: ap-northeast-2
  include_git_submodules: false
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: baba-eb-admin
  repository: null
  sc: gite
  workspace_type: Application
